apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "7dtd-server.fullname" . }}
  labels:
    {{- include "7dtd-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "7dtd-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "7dtd-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: 7dtd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
