apiVersion: v1
kind: Service
metadata:
  name: {{ include "7dtd-server.fullname" . }}
  labels:
    {{- include "7dtd-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .name }}
    {{- end }}
  selector:
    app: {{ include "7dtd-server.name" . }}
    release: {{ .Release.Name }}
